"""try

Revision ID: 8a261417eb30
Revises: effd9b354d75
Create Date: 2018-08-28 16:11:50.121906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a261417eb30'
down_revision = 'effd9b354d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tyre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('wheel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('diameter', sa.String(length=2), nullable=True),
    sa.Column('width', sa.String(length=4), nullable=True),
    sa.Column('offset', sa.String(length=4), nullable=True),
    sa.Column('bcd', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wheel_bcd'), 'wheel', ['bcd'], unique=False)
    op.create_index(op.f('ix_wheel_brand'), 'wheel', ['brand'], unique=False)
    op.create_index(op.f('ix_wheel_diameter'), 'wheel', ['diameter'], unique=False)
    op.create_index(op.f('ix_wheel_offset'), 'wheel', ['offset'], unique=False)
    op.create_index(op.f('ix_wheel_width'), 'wheel', ['width'], unique=False)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('followers')
    op.drop_index(op.f('ix_wheel_width'), table_name='wheel')
    op.drop_index(op.f('ix_wheel_offset'), table_name='wheel')
    op.drop_index(op.f('ix_wheel_diameter'), table_name='wheel')
    op.drop_index(op.f('ix_wheel_brand'), table_name='wheel')
    op.drop_index(op.f('ix_wheel_bcd'), table_name='wheel')
    op.drop_table('wheel')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('tyre')
    # ### end Alembic commands ###
